function writeCompileFileHeader(fid)
    fprintf(fid, '%6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s | %6s\n', ...
            'Name', 'Min X', 'Min Y', 'Min Z', 'Max X', 'Max Y', ...
            'Max Z', 'Std X', 'Std Y', 'Std Z', 'RMSE X', 'RMSE Y', ...
            'RMSE Z', 'Pixels');
    fprintf(fid, ['-------|', repmat('--------|', 1, 13), '---------\n']);
end